// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAESVwxwLthMZ8HO8-UC2vgH_PY_83UhfM',
    appId: '1:531527917036:web:b5d0938743772eba9a34c9',
    messagingSenderId: '531527917036',
    projectId: 'dhakalivenewsapp',
    authDomain: 'dhakalivenewsapp.firebaseapp.com',
    storageBucket: 'dhakalivenewsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jldDgDF-Nlx3_p59Zo5gVyBfFxWRFLY',
    appId: '1:531527917036:android:4794aa64ecb37f2e9a34c9',
    messagingSenderId: '531527917036',
    projectId: 'dhakalivenewsapp',
    storageBucket: 'dhakalivenewsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKgG4NNUmE7bHed_a544Y4gl8lHVi9MQ',
    appId: '1:531527917036:ios:415ec277f6589efc9a34c9',
    messagingSenderId: '531527917036',
    projectId: 'dhakalivenewsapp',
    storageBucket: 'dhakalivenewsapp.appspot.com',
    iosClientId: '531527917036-e8slm91n7er96j39op95lrl2a74834a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALKgG4NNUmE7bHed_a544Y4gl8lHVi9MQ',
    appId: '1:531527917036:ios:2a7754e38af64c5e9a34c9',
    messagingSenderId: '531527917036',
    projectId: 'dhakalivenewsapp',
    storageBucket: 'dhakalivenewsapp.appspot.com',
    iosClientId: '531527917036-o5an39qgscg73ijt6d5e5pb8h30vcu6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
